image: node:16

cache:
  paths:
    - node_modules/

pages:
  script:
    - npm install -g pnpm
    - pnpm install
    - pnpm run build
    - rm -rf public && mv out public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
